export const buttonsList = [
  { id: "b1", mark: "Notes", className: "dark" },
  { id: "b2", mark: "CE", className: "dark" },
  { id: "b3", mark: "C", className: "dark" },
  { id: "b4", mark: "⌫", className: "dark" },
  { id: "b5", mark: "1/x", className: "dark" },
  { id: "b6", mark: "x²", className: "dark" },
  { id: "b7", mark: "√", className: "dark" },
  { id: "b8", mark: "/", className: "dark" },
  { id: "b9", mark: "7", className: "light" },
  { id: "b10", mark: "8", className: "light" },
  { id: "b11", mark: "9", className: "light" },
  { id: "b12", mark: "x", className: "dark" },
  { id: "b13", mark: "4", className: "light" },
  { id: "b14", mark: "5", className: "light" },
  { id: "b15", mark: "6", className: "light" },
  { id: "b16", mark: "－", className: "dark" },
  { id: "b17", mark: "1", className: "light" },
  { id: "b18", mark: "2", className: "light" },
  { id: "b19", mark: "3", className: "light" },
  { id: "b20", mark: "+", className: "dark" },
  { id: "b21", mark: "+/-", className: "light" },
  { id: "b22", mark: "0", className: "light" },
  { id: "b23", mark: ",", className: "light" },
  { id: "b24", mark: "=", className: "confirm" },
];
